services:
  - type: web
    name: gestao-escolar-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python -m uvicorn simplified_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PRODUCTION
        value: True
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
        
  - type: web
    name: gestao-escolar-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    envVars:
      - key: REACT_APP_API_URL
        value: https://apinazarerodrigues.86dynamics.com.br/api
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /api/*
        destination: https://apinazarerodrigues.86dynamics.com.br/api/:splat
