services:
  - type: web
    name: gestao-escolar-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python -m uvicorn simplified_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PRODUCTION
        value: True
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
        
  - type: web
    name: gestao-escolar-frontend
    env: static
    buildCommand: echo "No build required for static files"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /api/*
        destination: https://gestao-escolar-api.onrender.com/api/:splat
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
